IF DB_ID('Achiras') IS NULL
		THROW 50001, 'Achiras NO existe', 1;
USE Achiras;
GO

ALTER DATABASE Achiras SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

	ALTER DATABASE Achiras SET RECOVERY SIMPLE;
	PRINT '[INFO] RECOVERY SIMPLE ok.';
	GO
	
	ALTER DATABASE Achiras SET READ_COMMITTED_SNAPSHOT ON; 	-- evitamos "si el Usuario A está actualizando una fila, el Usuario B que intenta leerla tiene que esperar a que el primero termine"
	PRINT '[INFO] READ_COMMITTED_SNAPSHOT ok.';
	GO
	
	ALTER DATABASE Achiras SET AUTO_CLOSE OFF;
	PRINT '[INFO] AUTO_CLOSE OFF ok.';
	GO
	
	ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = OFF;
	PRINT '[INFO] IDENTITY_CACHE = OFF ok.';
	GO
	
	ALTER DATABASE Achiras SET AUTO_SHRINK OFF;
	PRINT '[INFO] AUTO_SHRINK OFF ok.';
	GO

	ALTER DATABASE Achiras SET PAGE_VERIFY CHECKSUM;
	PRINT '[INFO] PAGE_VERIFY CHECKSUM ok.';
	GO
	
	ALTER DATABASE Achiras SET COMPATIBILITY_LEVEL = 150;
	PRINT '[INFO] COMPATIBILITY_LEVEL = 150 ok.';
	GO

ALTER DATABASE Achiras SET MULTI_USER;
GO


PRINT '[DONE] Configuracion lista';
GO
